module_name: Matomo Module
compatible_versions: 1.0.0+
author: thirty bees
category: statistics
tags:
  - matomo
  - piwik
  - google analytics
  - statistics
  - tracking
  - piwikanalyticsjs
description_short: The Matomo module allows you to install Piwik analytics on your site to track users.
description: description.md
images:
  - image-1.png
license: AFL
